workflow:
    - publish
shared:
    image: node:6
jobs:
    main:
        steps:
            - print: echo the main jobs started!
    publish:
        steps:
            - run: ./stuff.sh
            - next: echo blah2
